### PR TITLE
Add: AddKnownHost func

### LINKED ISSUE #2: Prompt to Add to knownhosts on new connections
This is an `ssh.HostKeyCallback` function I came up with and probably needs to be cleaned up. This was apart of an internal package I created for ssh connections. It doesn't print fingerprints as it should. But it was ignored because the tool I was creating was an internal project.

```go
func knownHostKey(hostname string, remote net.Addr, key ssh.PublicKey) error {
	knownFile := os.ExpandEnv("$HOME/.ssh/known_hosts")
	_, err := os.Stat(knownFile)
	if errors.Is(err, os.ErrNotExist) {
		f, ferr := os.OpenFile(knownFile, os.O_CREATE, 0600)
		if ferr != nil {
			return ferr
		}
		f.Close()
	}
	callback, err := knownhosts.New(knownFile)
	if err != nil {
		return err
	}
	err = callback(hostname, remote, key)
	if err == nil {
		return nil
	}
	var keyErr *knownhosts.KeyError
	if errors.As(err, &keyErr) && len(keyErr.Want) == 0 {
		r := bufio.NewReader(os.Stdin)
		fmt.Print("Unknown Host. Would you like to add it [y/N]: ")
		reply, rerr := r.ReadString('\n')
		if rerr != nil {
			return rerr
		}
		reply = strings.Replace(reply, "\n", "", -1)
		reply = strings.Replace(reply, "\r", "", -1)
		if strings.ToLower(reply) != "y" {
			return err
		}
		f, ferr := os.OpenFile(knownFile, os.O_WRONLY|os.O_APPEND, 0600)
		if ferr != nil {
			return ferr
		}
		defer f.Close()
		knownHost := knownhosts.Normalize(remote.String())
		_, err = f.WriteString(knownhosts.Line([]string{knownHost}, key) + "\n")
		if err != nil {
			return err
		}
		return nil
	}
	return err
}
```

I can add a PR if this is something you would like to support in this package.

### PR DESCRIPTION
**Pull request by melbahja**
add new function: AddKnownHost to add new hosts to known_hosts file and some improvements
- resolves #2

### CODE REVIEW

**Comment by melbahja** [comment]
@dixonwille I worked on a functionality and I want your opinion on it: 

To connect to a new host you should do this:

```go

client, err := goph.NewConn("root", "127.0.0.1", goph.Key("key/path"), func(host string, remote net.Addr, key ssh.PublicKey) error {

   // check your public key and return err if not trusted  

   // last param is the known_host file path, if empty fallback to $HOME/.ssh/known_hosts
   return goph.AddKnownHost(host, remote, key, "") 
})

```

**Comment by dixonwille** [comment]
Well, let me explain my function with examples, and allow a user to inject. The issue is, you need to call the Known_Host callback before asking (if that is what ther user wants to do). So you may need something more along the lines of.

```go
client, err := goph.NewConn("root", "127.0.0.1", goph.Key("key/path"), func(host string, remote net.Addr, key ssh.PublicKey) error {

  // check remote public key and return err if not trusted
  trusted, err := goph.CheckKnownHost(host, remote, key, "")
  if trusted {
    return nil
  }
  // CheckKnownHost failed (Could be because of man in the middle attack?)
  // EG. Host was in KnownHost but with a different key than expected
  if err != nil {
    return nil
  }
  // Unknown host so ask user
  fp := ssh.FingerprintSHA256(key)
  add := promptUserToAdd(host, key)
  if add {
    // last param is the known_host file path, if empty fallback to $HOME/.ssh/known_hosts
    return goph.AddKnownHost(host, remote, key, "") 
  }
})
```

But for the users who may not want to prompt you may want (which I think you already allow!)

```go
client, err := goph.NewConn("root", "127.0.0.1", goph.Key("key/path"), goph.DefaultKnownHost)
```

The `goph.CheckKnownHost` function does the heavy lifting and basically calls `goph.DefaultKnownHost`.

```go
func CheckKnownHost(hostname string, remote net.Addr, key ssh.PublicKey, knownHostFile string) (bool, error) {
        var (
		hostErr error
		fileErr error
		keyErr  *knownhosts.KeyError
	)

	// Fallback to default known_hosts file
	if knownFile == "" {
		knownFile = defaultPath
	}

	_, fileErr = os.Stat(knownFile)

	// Create if not exists
	if errors.Is(fileErr, os.ErrNotExist) {

		f, fileErr := os.OpenFile(knownFile, os.O_CREATE, 0600)

		if fileErr != nil {
			return false, fileErr
		}

		f.Close()
	}

	// Get host key callback
	callback, hostErr := KnownHosts(knownFile)

	if hostErr != nil {
		return false, hostErr
	}

	// check if host already exists
	hostErr = callback(host, remote, key)

	// Known host already exists
	if hostErr == nil {
		return true, nil
	}

        // Make sure that the error returned from the callback is host not in file error.
        // If keyErr.Want is greater than 0 length, that means host is in file with different key.
        if errors.As(hostErr, &keyErr) && len(keyErr.Want) > 0 {
                return false, keyErr
        }

        // Some other error occured and safest way to handle is to pass it back to user.
        if hostErr != nil {
                return false, hostErr
        }

        // Key is not trusted because it is not in the file
        return false, nil
}
```

They your `goph.AddKnownHost` can be condensed down to just adding the normalized line to the file.

**Comment by melbahja** [comment]
I think in case of key mismatch we should return `true, keyErr`
like this:
```go
if errors.As(hostErr, &keyErr) && len(keyErr.Want) > 0 {
      return true, keyErr
}
```
Because the host key already trusted, and the validation part should looks like this:

```go
trusted, err := goph.CheckKnownHost(host, remote, key, "")

// host key mismatch maybe because of man in the middle attack!
if trusted && err != nil {
		return errors.New("Key mismatch")
}
```

**Comment by melbahja** [comment]
@dixonwille CheckKnownHost func added, any feedback please?

**Comment by dixonwille** [comment]
Not sure if I agree with your comment. I am checking specifically if the keyErr is  a key mismatch in which case the host should not be trusted.

**Comment by dixonwille** [comment]
Other than that it looks good!

**Comment by dixonwille** [comment]
KnownHost holds both the hostname (which can be spoofed) and a public key to verify signiture from server. So on connection, server will send a signed packet using it's private key. If the public key cannot verify the signiture, then the host is using a different private key than what the user was expecting (Usually meaning a different server/man in the middle possiblity). I don't know exactly how SSH works but I do know server has to sign something that the client should verify for a secure connection.

So the host may be in the file, but the keys don't match is a huge warning sign that the server you trusted before is different now. One can either ignore it and overwrite (better make sure it is the host you were expecting), or don't attempt then connection.

**Comment by melbahja** [comment]
> Not sure if I agree with your comment. I am checking specifically if the keyErr is a key mismatch in which case the host should not be trusted.

I can return `false` on mismatch but how we can detect is host already in known hosts here ?
https://github.com/melbahja/goph/blob/improvements/examples/goph/main.go#L93

**Comment by melbahja** [comment]
> KnownHost holds both the hostname (which can be spoofed) and a public key to verify signiture from server. So on connection, server will send a signed packet using it's private key. If the public key cannot verify the signiture, then the host is using a different private key than what the user was expecting (Usually meaning a different server/man in the middle possiblity). I don't know exactly how SSH works but I do know server has to sign something that the client should verify for a secure connection.
> 
> So the host may be in the file, but the keys don't match is a huge warning sign that the server you trusted before is different now. One can either ignore it and overwrite (better make sure it is the host you were expecting), or don't attempt then connection.

Yes this what I'm talking about if you see this part:
https://github.com/melbahja/goph/blob/improvements/examples/goph/main.go#L93

**Comment by melbahja** [comment]
>  Because the host key already trusted, and the validation part should looks like this:

Here I want to say "Because the host key already In known hosts file", sorry about this.

**Comment by dixonwille** [comment]
`errors.As(hostErr, &keyErr) && len(keyErr.Want) > 0` that is the key mismatch check. may have to return a specific error if you want users to type check against that error?

**Comment by dixonwille** [comment]
I see you renamed the variables around, so really your first variable being returned is not `trusted` but instead `host was in file` and if eror exists, is whether or not it should be trusted or not.

**Comment by melbahja** [comment]
> `errors.As(hostErr, &keyErr) && len(keyErr.Want) > 0` that is the key mismatch check. may have to return a specific error if you want users to type check against that error?

Ok I think we should return `false` with a specific error

**Comment by melbahja** [comment]
> May want to add a comment above the CheckKnownHost func explaining what we just covered. Return values and how to use them appropriatly

What you think the best ? specific error with `true` or `false` with keyErr

**Comment by dixonwille** [comment]
Clearly documenting what the return values are is best course of action! I was assuming it was returning `trusted, err`. Your are actually returning `hostFound, err`. Two very different meanings when it comes to security!

**Comment by melbahja** [comment]
Yes, sorry if I confused you when I said ~~trusted~~

**Comment by melbahja** [comment]
@dixonwille can you check now please.

**Comment by dixonwille** [comment]
👍 Looks Good To Me!

**Comment by melbahja** [comment]
@dixonwille thank you for your help :heart:

**Pull request merged**
